elems:

  - src:  ^sudoers$
    dst:  /etc/sudoers
    only: f?sudoers

  - src:  ^(hosts)$
    dst:  /etc/<1>
    only: f?hosts

  - src:  ^(nsswitch\.conf)$
    dst:  /etc/<1>
    only: f?nsswitch

  - src:  ^udev/rules\.d/([0-9]+-hdparm\.rules)$
    dst:  /etc/udev/rules.d/<1>
    only: f?hdparm

  - src:  ^environment$
    dst:  "<%= var! :environment_path %>"
    only: f?hidpi

  - src:  ^mimeapps\.list$
    dst:  /etc/xdg/mimeapps.list
    only: f?mimeapps
    note: You should remove user-wide mimeapps files, usually located at ~/.mimeapps.list and ~/.local/share/applications/mimeapps.list

  - src:  ^mailcap$
    dst:  /etc/mailcap
    only: f?mailcap

  - src:  ^fonts/(.+)$
    dst:  /etc/fonts/conf.avail/<1>
    only: f?fonts
    note: |
      You may want to enable the installed fonts configuration by doing
      - In Gentoo -> sudo eselect fontconfig enable <name>
      - In any other Linux distro -> sudo ln -s /etc/fonts/conf.avail/<name> /etc/fonts/conf.d


# vim: set filetype=eruby.yaml :
