elems:

  - src:  ^(hosts)$
    dst:  /etc/<1>
    only: f?hosts

  - src:  ^(nsswitch\.conf)$
    dst:  /etc/<1>
    only: f?nsswitch

  - src:  ^udev/rules\.d/([0-9]+-hdparm\.rules)$
    dst:  /etc/udev/rules.d/<1>
    only: f?hdparm

  - src:  ^env\.d/([0-9]+hidpi)$
    dst:  /etc/env.d/<1>
    only: f?hidpi


# vim: set filetype=eruby.yaml :
