elems:

  - src:  ^(nsswitch\.conf)$
    dst:  /etc/<1>
    only: f?nsswitch

  - src:  ^udev/rules\.d/([0-9]+-hdparm\.rules)$
    dst:  /etc/udev/rules.d/50-hdparm.rules
    only: f?hdparm


# vim: set filetype=eruby.yaml :
